### PR TITLE
Terminate if access to message queue is lost

### PR DESCRIPTION
**Pull request by michaellass**
When the message queue is destroyed, libgpiod_pulsein will loop on
msgrcv() and hog the CPU. There is no way to recover from this situation
so just terminate with an error message in this case.

This situation can occur when a background task (e.g., a systemd
service) runs under a non-system user and uses libgpiod_pulsein. When
that user logs out from all of its sessions, logind in its default
configutation will destroy all remaining message queues of that user.

Refs adafruit/Adafruit_CircuitPython_DHT#50

### CODE REVIEW

**Comment by ladyada** [comment]
Thanks! can anyone else in that thread also try this change? good to get a few testers :)

**Comment by michaellass** [comment]
Of course @Kraka23 or @darton may test this modification in their own setup. However I don't really consider it necessary.

Here is what I did to test this change independent of any python script or systemd. Required for this test is a raspberry pi with more than 1 CPU core such that we can see the difference between 100% and 200% CPU.

```
Terminal 1:										Terminal 2:
-----------										-----------

git clone https://github.com/michaellass/libgpiod_pulsein.git

cd libgpiod_pulsein/src

make

ipcmk --mode 600 --queue

ipcs -q # note down key of message queue with ID shown before by ipcmk

# Convert key from hex to dec. In this example: 0x0b9ae786 -> 194701190

# in the following command, adjust queue id and the pin number (last arg)
./libgpiod_pulsein --pulses 81 --queue 194701190 -i gpiochip0 2

											# Run top and note that libgpiod_pulsein uses 100% CPU. This is the
											# thread that reads the sensor (since it is not paused). This is
											# expected and desired behavior.

											# replace the queue id by what was shown before by ipcmk
											ipcrm --queue-id 15

											# Run top again and note that libgpiod_pulsein now uses 200% CPU. The
											# thread reading the message queue now requires 100% as well. This
											# is what this PR is about to fix.

# Press Ctrl+C to terminate libgpiod_pulsein

git checkout handle_msq_loss

make

ipcmk --mode 600 --queue

ipcs -q # note down key of message queue with ID shown before by ipcmk

# Convert key from hex to dec. In this example: 0x9091b3b2 -> 2425467826

# in the following command, adjust queue id and the pin number (last arg)
./libgpiod_pulsein --pulses 81 --queue 2425467826 -i gpiochip0 2

											# Run top and note that libgpiod_pulsein uses 100% CPU. This is the
											# thread that reads the sensor (since it is not paused). This is
											# expected and desired behavior.

											# replace the queue id by what was shown before by ipcmk
											ipcrm --queue-id 16

# libgpiod_pulsein will terminate with an error message:
# "Lost access to message queue"
# This is the best we can do in this situation.
```

I also replaced the `libgpiod_pulsein` binary on my personal logging device which I use to frequently record data from a DHT22 sensor. So far I do not experience any issues. However, we may want to wait for a couple of days before merging this, just to make sure that this error condition (EINVAL) does not occur during normal operation.

**Comment by michaellass** [comment]
I never noticed any unexpected side-effects from this change. Is there anything left to do here? Terminating with an error message instead of hogging the CPU would help people running into https://github.com/adafruit/Adafruit_CircuitPython_DHT/issues/50 to figure out what's going on.

**Comment by michaellass** [comment]
Timeout

**Comment by darton** [comment]
Is there a chance that this amendment will be adopted ?

**Comment by ladyada** [comment]
you can try to re-submit the PR, the original author closed it

**Comment by michaellass** [comment]
I can repoen it but I don't wont to have an open PR in my dashboard for another year. Please decide if you want to accept this change or not.

**Comment by ladyada** [comment]
we were waiting for folks to try out the change - @darton @scaidermern please test it out so we can make sure no bugs are introduced!

**Review by makermelissa — APPROVED** [review]
Code change itself looks good. I'm waiting on others to test first.

**Comment by darton** [comment]
It works stably for me.

**Pull request merged**
